name: AYE Loader CI
on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Install AHK
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install autohotkey.install --params='/DefaultVer:A32'
    - name: Build Loader
      run: COMPILE.bat
    - name: Success Notice
      - uses: actions/upload-artifact@v2
        with:
          name: aye-loader.exe
          path: loader.exe
        
