name: AYE Loader CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: CI Notice
      run: |
        curl -H "Content-Type: application/json" -d '{"chat_id":"'"${{ secrets.CHAT_ID }}"'","text":"<b>NEW PUSH IN $GITHUB_REPOSITORY</b>\n\nCI build started!","parse_mode":"html"}' https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage
    - uses: actions/checkout@v2
    - name: Sex with anime
      run: |
        Invoke-WebRequest https://gist.githubusercontent.com/rfoxxxy/7597ab96d3dc6342069922f7c18fb2cf/raw/128e94c5c815be9715a0ac471a9610af9d7c7bc6/Convert-Encoding.ps1 -OutFile sex.ps1
        ./sex.ps1 .
        ./sex.ps1 ./Lib
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Install AHK
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install autohotkey.install --params='/DefaultVer:A32'
    - name: Build Loader
      run: ./COMPILE.bat
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - if: steps.build.outputs.status == 'failure'
      name: Failure Notice
      run: |
        curl -H "Content-Type: application/json" -d '{"chat_id":"'"${{ secrets.CHAT_ID }}"'","text":"CI build on push in <code>$GITHUB_REPOSITORY</code> <b>failed!</b>","parse_mode":"html"}' https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage
        exit 1
    - if: steps.build.outputs.status != 'failure'
      name: Success Notice
      run: |
        curl -H "Content-Type: application/json" -d '{"chat_id":"'"${{ secrets.CHAT_ID }}"'","text":"CI build on push in <code>$GITHUB_REPOSITORYr</code> <b>passed!</b>","parse_mode":"html"}' https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage

